### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by Nku-cs-dsc** [danmohaha/CVPRW2019_Face_Artifacts#14]
Hi~ Thank you for your excellent work on the deepfake detection task. We want to cite your paper and hope to test your pre-trained model on our newly proposed dataset. Can you publish your pre-trained model? thank you very much !

**Comment by yuezunli** [comment]
Hi, I just noticed my google drive was shut down. The model has been relocated to onedrive (https://1drv.ms/u/s!As4tun0sWfKsgdJFVA9qdnRmqKbfpg?e=4Hrvf6).

**Comment by Nku-cs-dsc** [comment]
thx~
